package com.okliu.springboot.entity;

public class Clazz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.id
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.name
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.classTeacher
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    private String classteacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.lecturer
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    private String lecturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.state
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.id
     *
     * @return the value of tb_class.id
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.id
     *
     * @param id the value for tb_class.id
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.name
     *
     * @return the value of tb_class.name
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.name
     *
     * @param name the value for tb_class.name
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.classTeacher
     *
     * @return the value of tb_class.classTeacher
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public String getClassteacher() {
        return classteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.classTeacher
     *
     * @param classteacher the value for tb_class.classTeacher
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public void setClassteacher(String classteacher) {
        this.classteacher = classteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.lecturer
     *
     * @return the value of tb_class.lecturer
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.lecturer
     *
     * @param lecturer the value for tb_class.lecturer
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.state
     *
     * @return the value of tb_class.state
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.state
     *
     * @param state the value for tb_class.state
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}