package com.okliu.springboot.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.okliu.springboot.entity.Clazz;

@Mapper
public interface ClazzDao {
	/**
	  * �ֶ����
	  * ��ѯ����
	 */
	List<Clazz> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    Clazz selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbg.generated Thu Dec 20 09:58:25 CST 2018
     */
    int updateByPrimaryKey(Clazz record);
}